mh_column_dict = {
	0: 'KDA',
	1: 'largest_killing_spree',
	2: 'largest_multi_kill',
	3: 'first_blood',
	4: 'total_damage_dealt_to_champions',
	5: 'physical_damage_dealt_to_champions',
	6: 'magic_damage_dealt_to_champions',
	7: 'true_damage_dealt_to_champions',
	8: 'total_damage_dealt',
	9: 'physical_damage_dealt',
	10: 'magic_damage_dealt',
	11: 'true_damage_dealt',
	12: 'largest_critical_strike',
	13: 'damage_dealt_to_objectives',
	14: 'damage_dealt_to_turrets',
	15: 'total_heal',
	16: 'total_damage_taken',
	17: 'physical_damage_taken',
	18: 'magical_damage_taken',
	19: 'true_damage_taken',
	20: 'wards_placed',
	21: 'wards_killed',
	22: 'sight_wards_bought_in_game',
	23: 'vision_wards_bought_in_game',
	24: 'earned_gold',
	25: 'gold_spent',
	26: 'minion_kills',
	27: 'neutral_minions_kills',
	28: "neutral_minions_kills_team_jungle",
	29: 'neutral_minions_kills_enemy_jungle'
}


# correct_number_dict = {
# 	**dict.fromkeys(["Zero"], 0),
# 	**dict.fromkeys(["One"], 1),
# 	**dict.fromkeys(["Two"], 2),
# 	**dict.fromkeys(["Three"], 3),
# 	**dict.fromkeys(["Four"], 4),
# 	**dict.fromkeys(["Five"], 5),
# 	**dict.fromkeys(["Six"], 6),
# 	**dict.fromkeys(["Seven"], 7),
# 	**dict.fromkeys(["Eight"], 8),
# 	**dict.fromkeys(["Nine"], 9),
# 	**dict.fromkeys(["Ten"], 10),
# 	**dict.fromkeys(["Eleven"], 11),
# 	**dict.fromkeys(["Twelve"], 12),
# 	**dict.fromkeys(["Thirteen"], 13),
# 	**dict.fromkeys(["Fourteen"], 14),
# 	**dict.fromkeys(["Fifteen"], 15),
# 	**dict.fromkeys(["Sixteen"], 16),
# 	**dict.fromkeys(["Seventeen"], 17),
# 	**dict.fromkeys(["Eighteen"], 18),
# 	**dict.fromkeys(["One"], 19)
# }